src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_First_Name__c.field-meta.xml
<CustomField>
    <fullName>MBMS_First_Name__c</fullName>
    <description>A field that stores a first name of the Artist.</description>
    <inlineHelpText>First name of the Artist.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Last_Name__c</fullName>
    <description>A field that stores a last name of the Artist.</description>
    <inlineHelpText>Last name of the Artist.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Artist.</description>
    <inlineHelpText>Artist status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArtistTriggerUtility.cls
public class ArtistTriggerUtility {
    public static void updateArtistNames(List<MBMS_Artist__c> artists) {
        for (MBMS_Artist__c artist : artists) {
            artist.Name = String.format('{0} {1}', new List<String> { artist.MBMS_First_Name__c, artist.MBMS_Last_Name__c });
        }
    }
    
    public static void updateArtistStatusComments(List<MBMS_Artist__c> artists) {
        for (MBMS_Artist__c artist : artists) {
            artist.MBMS_Status_Comment__c = MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT;
        }
    }
    
    public static void removeRelatedMovieActors(List<MBMS_Artist__c> artists) {
        Set<Id> artistIds = (new Map<Id, MBMS_Artist__c>(artists)).keySet();
        List<MBMS_Movie_Actor__c> movieActors = [SELECT Id FROM MBMS_Movie_Actor__c WHERE MBMS_Artist__r.Id IN :artistIds];
        
        delete movieActors;
    }

    public static void notifyApprovers(List<MBMS_Artist__c> artists) {
        Group approversQueue = [SELECT Id
                                FROM Group WHERE Type = :MBMS_Constants.QUEUE_GROUP_TYPE
                                AND Name = :MBMS_Constants.APPROVERS_QUEUE
                                LIMIT 1];
        
        List<GroupMember> approvers = [SELECT UserOrGroupId
                                       FROM GroupMember
                                       WHERE GroupId = :approversQueue.Id];

        for (MBMS_Artist__c artist : artists) {
            if (artist.MBMS_Status__c == MBMS_Constants.MBMS_STATUS_APPROVED) {
                continue;
            }

            for (GroupMember approver : approvers) {
                CustomNotification notification = new CustomNotification(MBMS_Constants.PLEASE_TAKE_ACTION, String.format(MBMS_Constants.RECORD_TO_APPROVE_PATTERN, new List<String> { artist.Name, artist.Id }), new Set<String> { approver.UserOrGroupId }, artist.Id);
                notification.send();
            }
        }
    }
}