src/objects/MBMS_Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies</relationshipLabel>
        <relationshipName>Movies_Director</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writer</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies (Writer)</relationshipLabel>
        <relationshipName>Movies_Writer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

src/classes/MoviesListController.cls
public with sharing class MoviesListController {
    @AuraEnabled
    public static List<MBMS_Movie__c> getMoviesList() {
        return [SELECT Id, Name, MBMS_Title__c,
                MBMS_Director__r.Name, MBMS_Writer__r.Name
                FROM MBMS_Movie__c];
    }
    
    public static List<MBMS_Movie__c> getRequiringActionMovies() {
        return [SELECT Id, Name, MBMS_Status__c, CreatedDate
                FROM MBMS_Movie__c
                WHERE MBMS_Status__c IN (:Constants.STATUS_INITIAL, :Constants.STATUS_REJECTED)
                ORDER BY CreatedDate];
    }
    
    @AuraEnabled
    public static Boolean areMoviesAvailable() { 
        return getMoviesList().size() > 0 ;
    }
}