src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Book.</description>
        <inlineHelpText>Book status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Book record.</description>
        <inlineHelpText>Status of the Book record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Book__c/fields/MBMS_Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Previous_Status__c</fullName>
    <description>A field that stores a previous status of the Book record.</description>
    <inlineHelpText>Previous Status of the Book record.</inlineHelpText>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookTriggerHandlerTest.cls
@isTest
private class BookTriggerHandlerTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        MBMS_Book__c book = new BookBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void triggerShouldUpdateBookName() {
        MBMS_Book__c book = [
            SELECT
                Name,
                MBMS_Title__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(book.MBMS_Title__c, book.Name, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'Name', book.MBMS_Title__c }));
    }
    
    @isTest
    static void triggerShouldUpdateBookStatusComment() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Status_Comment__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.INITIAL_STATUS_COMMENT, book.MBMS_Status_Comment__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status_Comment__c', Constants.INITIAL_STATUS_COMMENT }));
    }

    @isTest
    static void triggerShouldUpdateRecordOwner() {
        MBMS_Book__c book = [
            SELECT
                OwnerId
            FROM MBMS_Book__c
            LIMIT 1
        ];

        book.MBMS_Status__c = Constants.STATUS_REJECTED;

        Test.startTest();
        update book;
        Test.stopTest();

        Group approversQueue = SObjectsSelector.getApproversQueue();

        book = [
            SELECT
                OwnerId
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(approversQueue.Id, book.OwnerId, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'OwnerId', approversQueue.Id }));
    }

    @isTest
    static void triggerShouldUpdatePreviousStatus() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Status__c
            FROM MBMS_Book__c
            LIMIT 1
        ];

        String expectedPreviousStatus = book.MBMS_Status__c;
        book.MBMS_Status__c = Constants.STATUS_REJECTED;

        Test.startTest();
        update book;
        Test.stopTest();

        book = [
            SELECT
                MBMS_Previous_Status__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(expectedPreviousStatus, book.MBMS_Previous_Status__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Previous_Status__c', expectedPreviousStatus }));
    }
}