src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Artist_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist News.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Artist News</relationshipLabel>
        <relationshipName>Artist_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist News</label>
    <nameField>
        <label>Artist News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artist News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ArtistNewsController.cls
public with sharing class ArtistNewsController {
    @AuraEnabled(cacheable=true)
    public static MBMS_Artist_News__c getLatestArtistNews() {
        return [
            SELECT
                MBMS_Title__c,
                MBMS_Content__c,
                MBMS_Tags__c,
                MBMS_Image_URL__c,
                CreatedDate,
                MBMS_Artist__r.Name
            FROM MBMS_Artist_News__c
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static MBMS_Artist_News__c getLatestArtistNewsByArtistId(String artistId) {
        return [
            SELECT
                MBMS_Title__c,
                MBMS_Content__c,
                MBMS_Tags__c,
                MBMS_Image_URL__c,
                CreatedDate,
                MBMS_Artist__r.Name
            FROM MBMS_Artist_News__c
            WHERE MBMS_Artist__c = :artistId
            ORDER BY CreatedDate DESC
            LIMIT 1];
    }
}