src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Book News.</description>
    <fields>
        <fullName>MBMS_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Book object.</description>
        <inlineHelpText>Book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>MBMS_Book__c</referenceTo>
        <relationshipLabel>Book News</relationshipLabel>
        <relationshipName>Book_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book News</label>
    <nameField>
        <label>Book News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookNewsBuilder.cls
public class BookNewsBuilder {   
    private MBMS_Book_News__c bookNews;
    
    public BookNewsBuilder create() {
        this.bookNews = new MBMS_Book_News__c();
        return this;
    }
    
    public BookNewsBuilder withName(String name) {
        this.bookNews.Name = name;
        return this;
    }
    
    public BookNewsBuilder withTitle(String title) {
        this.bookNews.MBMS_Title__c = title;
        return this;
    }
    
    public BookNewsBuilder withContent(String content) {
        this.bookNews.MBMS_Content__c = content;
        return this;
    }
    
    public BookNewsBuilder withTags(List<String> tags) {
        this.bookNews.MBMS_Tags__c = String.join(tags, ';');
        return this;
    }
    
    public BookNewsBuilder withBook(MBMS_Book__c book) {
        this.bookNews.MBMS_Book__c = book.Id;
        return this;
    }
    
    public BookNewsBuilder withImageURL(String imageURL) {
        this.bookNews.MBMS_Image_URL__c = imageURL;
        return this;
    }
    
    /*
     Should not be used in the loops due to SOQL limit - it inserts related fields.
     This method is used to create a single record (with all fields) for test purposes.
     */
    public MBMS_Book_News__c buildWithAllFields() {
        MBMS_Book__c book = new BookBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        
        return this
            .withBook(book)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withContent(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTags(new List<String> { MBMS_Constants.MBMS_TEST_STRING_VALUE, MBMS_Constants.MBMS_TEST_STRING_VALUE })
            .withImageURL(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .build();
    }
    
    public MBMS_Book_News__c buildWithAllFieldsAndInsert() {
        this.bookNews = this.buildWithAllFields();
        insert bookNews;
        return bookNews;
    }
    
    public MBMS_Book_News__c build() {       
        return bookNews;
    }
    
    public MBMS_Book_News__c buildAndInsert() {       
        insert bookNews;
        return this.build();
    }
}