src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Book News.</description>
    <fields>
        <fullName>MBMS_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Book object.</description>
        <inlineHelpText>Book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>MBMS_Book__c</referenceTo>
        <relationshipLabel>Book News</relationshipLabel>
        <relationshipName>Book_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book News</label>
    <nameField>
        <label>Book News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookNewsControllerTest.cls
@isTest
public class BookNewsControllerTest {
    @testSetup
    static void testDataSetup() {
        new BookNewsBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
    }
    
    @isTest
    static void shouldThrowException() {
        Test.startTest();
        MBMS_Book_News__c bookNews = [SELECT Id FROM MBMS_Book_News__c LIMIT 1];
        delete bookNews;
        
        Integer exceptionsCount = 0;
        
        try {
            bookNews = BookNewsController.getLatestBookNews();
        } catch (Exception e) {
            exceptionsCount++;
            System.assertNotEquals(null, e);
            System.assertEquals('List has no rows for assignment to SObject', e.getMessage());
        }
        Test.stopTest();
        
        System.assert(exceptionsCount > 0);
    }
    
    @isTest
    static void shouldReturnBookNews() {
        Test.startTest();
        MBMS_Book_News__c bookNews = BookNewsController.getLatestBookNews();
        Test.stopTest();
        
        System.assertNotEquals(null, bookNews);
    }
    
    @isTest
    static void shouldReturnBookNewsByBookId() {
        Test.startTest();
        MBMS_Book__c book = [SELECT Id FROM MBMS_Book__c LIMIT 1];
        MBMS_Book_News__c bookNews = BookNewsController.getLatestBookNewsByBookId(book.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, bookNews);
    }
}