src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie News.</description>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipLabel>Movie News</relationshipLabel>
        <relationshipName>Movie_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie News</label>
    <nameField>
        <label>Movie News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieNewsBuilder.cls
public class MovieNewsBuilder {   
    private MBMS_Movie_News__c movieNews;
    
    public MovieNewsBuilder create() {
        this.movieNews = new MBMS_Movie_News__c();
        return this;
    }
    
    public MovieNewsBuilder withName(String name) {
        this.movieNews.Name = name;
        return this;
    }
    
    public MovieNewsBuilder withTitle(String title) {
        this.movieNews.MBMS_Title__c = title;
        return this;
    }
    
    public MovieNewsBuilder withContent(String content) {
        this.movieNews.MBMS_Content__c = content;
        return this;
    }
    
    public MovieNewsBuilder withTags(List<String> tags) {
        this.movieNews.MBMS_Tags__c = String.join(tags, ';');
        return this;
    }
    
    public MovieNewsBuilder withMovie(MBMS_Movie__c movie) {
        this.movieNews.MBMS_Movie__c = movie.Id;
        return this;
    }
    
    public MovieNewsBuilder withImageURL(String imageURL) {
        this.movieNews.MBMS_Image_URL__c = imageURL;
        return this;
    }
    
    /*
     Should not be used in the loops due to SOQL limit - it inserts related fields.
     This method is used to create a single record (with all fields) for test purposes.
     */
    public MBMS_Movie_News__c buildWithAllFields() {
        MBMS_Movie__c movie = new MovieBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        
        return this
            .withMovie(movie)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withContent(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTags(new List<String> { MBMS_Constants.MBMS_TEST_STRING_VALUE, MBMS_Constants.MBMS_TEST_STRING_VALUE })
            .withImageURL(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .build();
    }
    
    public MBMS_Movie_News__c buildWithAllFieldsAndInsert() {
        this.movieNews = this.buildWithAllFields();
        insert movieNews;
        return movieNews;
    }
    
    public MBMS_Movie_News__c build() {       
        return movieNews;
    }
    
    public MBMS_Movie_News__c buildAndInsert() {       
        insert movieNews;
        return this.build();
    }
}