src/objects/MBMS_Batch_Log__c.object
<CustomObject>
    <description>This is an object for storing information about batch runs.</description>
    <fields>
        <fullName>MBMS_Batch_Name__c</fullName>
        <description>Batch name.</description>
        <label>Batch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Message__c</fullName>
        <description>Main log message.</description>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Records_Processed__c</fullName>
        <description>Amount of records processed by the batch.</description>
        <label>Records Processed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Batch Log</label>
    <nameField>
        <label>Batch Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchLogBuilder.cls
public class BatchLogBuilder {
    private MBMS_Batch_Log__c batchLog;
    
    public BatchLogBuilder create() {
        this.batchLog = new MBMS_Batch_Log__c();
        return this;
    }
    
    public BatchLogBuilder withName(String name) {
        this.batchLog.Name = name;
        return this;
    }
    
    public BatchLogBuilder withBatchName(String batchName) {
        this.batchLog.MBMS_Batch_Name__c = batchName;
        return this;
    }
    
    public BatchLogBuilder withMessage(String message) {
        this.batchLog.MBMS_Message__c = message;
        return this;
    }
    
    public BatchLogBuilder withRecordsProcessed(Integer recordsProcessed) {
        this.batchLog.MBMS_Records_Processed__c = recordsProcessed;
        return this;
    }
    
    public MBMS_Batch_Log__c buildWithAllFields() {
        return this
            .withName(Constants.TEST_STRING_VALUE)
            .withMessage(Constants.TEST_STRING_VALUE)
            .withRecordsProcessed(Constants.TEST_NUMBER)
            .build();
    }
    
    public MBMS_Batch_Log__c buildWithAllFieldsAndInsert() {
        this.batchLog = this.buildWithAllFields();
        insert this.batchLog;
        return this.batchLog;
    }
    
    public MBMS_Batch_Log__c build() {
        return this.batchLog;
    }
    
    public MBMS_Batch_Log__c buildAndInsert() {
        insert this.batchLog;
        return this.build();
    }
}