src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Book record.</description>
        <inlineHelpText>Status of the Book record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BooksListController.cls
public with sharing class BooksListController {
    @AuraEnabled
    public static List<MBMS_Book__c> getBooksList() {
        return [SELECT Id, Name, MBMS_Title__c
                FROM MBMS_Book__c];
    }
    
    public static List<MBMS_Book__c> getRequiringActionBooks() {
        return [SELECT Id, Name, MBMS_Status__c, CreatedDate
                FROM MBMS_Book__c
                WHERE MBMS_Status__c IN (:MBMS_Constants.MBMS_STATUS_INITIAL, :MBMS_Constants.MBMS_STATUS_REJECTED)
                ORDER BY CreatedDate];
    }
}