src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Artist_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist News.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Artist News</relationshipLabel>
        <relationshipName>Artist_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist News</label>
    <nameField>
        <label>Artist News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artist News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArtistNewsBuilder.cls
public class ArtistNewsBuilder {   
    private MBMS_Artist_News__c artistNews;
    
    public ArtistNewsBuilder create() {
        this.artistNews = new MBMS_Artist_News__c();
        return this;
    }
    
    public ArtistNewsBuilder withName(String name) {
        this.artistNews.Name = name;
        return this;
    }
    
    public ArtistNewsBuilder withTitle(String title) {
        this.artistNews.MBMS_Title__c = title;
        return this;
    }
    
    public ArtistNewsBuilder withContent(String content) {
        this.artistNews.MBMS_Content__c = content;
        return this;
    }
    
    public ArtistNewsBuilder withTags(List<String> tags) {
        this.artistNews.MBMS_Tags__c = String.join(tags, ';');
        return this;
    }
    
    public ArtistNewsBuilder withArtist(MBMS_Artist__c artist) {
        this.artistNews.MBMS_Artist__c = artist.Id;
        return this;
    }
    
    public ArtistNewsBuilder withImageURL(String imageURL) {
        this.artistNews.MBMS_Image_URL__c = imageURL;
        return this;
    }
    
    /*
     Should not be used in the loops due to SOQL limit - it inserts related fields.
     This method is used to create a single record (with all fields) for test purposes.
     */
    public MBMS_Artist_News__c buildWithAllFields() {
        MBMS_Artist__c artist = new ArtistBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        
        return this
            .withArtist(artist)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withContent(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTags(new List<String> { MBMS_Constants.MBMS_TEST_STRING_VALUE, MBMS_Constants.MBMS_TEST_STRING_VALUE })
            .withImageURL(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .build();
    }
    
    public MBMS_Artist_News__c buildWithAllFieldsAndInsert() {
        this.artistNews = this.buildWithAllFields();
        insert artistNews;
        return artistNews;
    }
    
    public MBMS_Artist_News__c build() {       
        return artistNews;
    }
    
    public MBMS_Artist_News__c buildAndInsert() {       
        insert artistNews;
        return this.build();
    }
}