src/objects/MBMS_Movie__c.object
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Movie.</description>
    <inlineHelpText>Movie status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie_Photo__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie Photo.</description>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipName>Photos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Photo_URL__c</fullName>
        <description>A field that stores a Photo URL.</description>
        <inlineHelpText>Photo URL.</inlineHelpText>
        <label>Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Movie Photo.</description>
        <inlineHelpText>Movie Photo status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Movie Photo record.</description>
        <inlineHelpText>Status of the Movie Photo record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Movie Photo</label>
    <nameField>
        <label>Movie Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoviePhotoBuilder.cls
public class MoviePhotoBuilder {
    private MBMS_Movie_Photo__c moviePhoto;
    
    public MoviePhotoBuilder create() {
        this.moviePhoto = new MBMS_Movie_Photo__c();
        return this;
    }
    
    public MoviePhotoBuilder withName(String name) {
        this.moviePhoto.Name = name;
        return this;
    }
    
    public MoviePhotoBuilder withMovie(MBMS_Movie__c movie) {
        this.moviePhoto.MBMS_Movie__c = movie.Id;
        return this;
    }
    
    public MoviePhotoBuilder withPhotoURL(String photoURL) {
        this.moviePhoto.MBMS_Photo_URL__c = photoURL;
        return this;
    }

    public MoviePhotoBuilder withStatus(String status) {
        this.moviePhoto.MBMS_Status__c = status;
        return this;
    }
    
    public MoviePhotoBuilder withStatusComment(String statusComment) {
        this.moviePhoto.MBMS_Status_Comment__c = statusComment;
        return this;
    }
    
    /*
     Should not be used in the loops due to SOQL limit - it inserts related fields.
     This method is used to create a single record (with all fields) for test purposes.
     */
    public MBMS_Movie_Photo__c buildWithAllFields() {
        MBMS_Movie__c movie = new MovieBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        
        return this
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withMovie(movie)
            .withPhotoURL(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withStatus(MBMS_Constants.MBMS_STATUS_APPROVED)
            .withStatusComment(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .build();
    }
    
    public MBMS_Movie_Photo__c buildWithAllFieldsAndInsert() {
        this.moviePhoto = this.buildWithAllFields();
        insert moviePhoto;
        return moviePhoto;
    }
    
    public MBMS_Movie_Photo__c build() {       
        return moviePhoto;
    }
    
    public MBMS_Movie_Photo__c buildAndInsert() {       
        insert moviePhoto;
        return this.build();
    }
}