src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Birthplace__c</fullName>
        <description>A field that stores a birthplace (country / city) of the Artist.</description>
        <inlineHelpText>Birthplace of the artist.</inlineHelpText>
        <label>Birthplace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Date_of_Birth__c</fullName>
        <description>A field that stores a date of birth of the Artist.</description>
        <inlineHelpText>Date of birth of the artist.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MBMS_Date_of_Death__c</fullName>
        <description>A field that stores a date of death of the Artist.</description>
        <inlineHelpText>Date of death of the artist.</inlineHelpText>
        <label>Date of Death</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArtistsListController.cls
public with sharing class ArtistsListController {
    @AuraEnabled
    public static List<MBMS_Artist__c> getArtistsList() {
        return [SELECT Id, Name, MBMS_Birthplace__c,
                MBMS_Date_of_Birth__c, MBMS_Date_of_Death__c
                FROM MBMS_Artist__c];
    }
    
    public static List<MBMS_Artist__c> getRequiringActionArtists() {
        return [SELECT Id, Name, MBMS_Status__c, CreatedDate
                FROM MBMS_Artist__c
                WHERE MBMS_Status__c IN (:Constants.STATUS_INITIAL, :Constants.STATUS_REJECTED)
                ORDER BY CreatedDate];
    }
    
    @AuraEnabled
    public static Boolean areArtistsAvailable() { 
        return getArtistsList().size() > 0;
    }
}