src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Artist_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist News.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Artist News</relationshipLabel>
        <relationshipName>Artist_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist News</label>
    <nameField>
        <label>Artist News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artist News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ArtistNewsBuilderTest.cls
@isTest
private class ArtistNewsBuilderTest {
    @testSetup
    static void testDataSetup() {
        new ArtistNewsBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
    }
    
    @isTest
    static void artistNewsShouldNotBeNull() {
        MBMS_Artist_News__c artistNews = new ArtistNewsBuilder()
            .create()
            .build();
        
        System.assertNotEquals(null, artistNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist_News__c' }));
    }
    
    @isTest
    static void insertedArtistNewsShouldNotBeNull() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                Id
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, artistNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist_News__c' }));
    }
    
    @isTest
    static void artistNewsShouldHaveName() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                Name
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, artistNews.Name, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist_News__c' }));
    }
    
    @isTest
    static void artistNewsShouldHaveTitle() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                MBMS_Title__c
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, artistNews.MBMS_Title__c, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Title__c' }));
    }
    
    @isTest
    static void artistNewsShouldHaveContent() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                MBMS_Content__c
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, artistNews.MBMS_Content__c, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Content__c' }));
    }
    
    @isTest
    static void artistNewsShouldHaveTags() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                MBMS_Tags__c
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assert(artistNews.MBMS_Tags__c.contains(Constants.TEST_STRING_VALUE), String.format(Constants.FIELD_SHOULD_CONTAIN_PATTERN, new List<String> { 'MBMS_Tags__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void artistNewsShouldHaveArtist() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                MBMS_Artist__c
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, artistNews.MBMS_Artist__c, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist__c' }));
    }
    
    @isTest
    static void artistNewsShouldHaveImageURL() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                MBMS_Image_URL__c
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, artistNews.MBMS_Image_URL__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Image_URL__c', Constants.TEST_STRING_VALUE }));
    }
}