src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieActorBuilderTest.cls
@isTest
private class MovieActorBuilderTest {
    @testSetup
    static void testDataSetup() {
        MBMS_Artist__c artist = new ArtistBuilder()
            .withRoles(new List<String> { MBMS_Constants.MBMS_ROLE_AUTHOR, MBMS_Constants.MBMS_ROLE_ACTOR })
            .buildAndInsert();
        
        MBMS_Movie__c movie = new MovieBuilder()
            .buildAndInsert();
        
        MBMS_Movie_Actor__c movieActor = new MovieActorBuilder()
            .withActor(artist)
            .withMovie(movie)
            .buildAndInsert();
    }
    
    @isTest
    static void movieActorShouldNotBeNull() {
        Test.startTest();        
        MBMS_Movie_Actor__c movieActor = new MovieActorBuilder().build();
        Test.stopTest();
        
        System.assertNotEquals(null, movieActor);
    }
    
    @isTest
    static void insertedMovieActorShouldNotBeNull() {
        Test.startTest();        
        MBMS_Movie_Actor__c movieActor = [SELECT Id
                                          FROM MBMS_Movie_Actor__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movieActor);
    }
    
    @isTest
    static void movieActorShouldHaveAnActor() {
        Test.startTest();        
        MBMS_Movie_Actor__c movieActor = [SELECT MBMS_Artist__c
                                          FROM MBMS_Movie_Actor__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movieActor.MBMS_Artist__c);
    }
    
    @isTest
    static void movieActorShouldHaveAMovie() {
        Test.startTest();        
        MBMS_Movie_Actor__c movieActor = [SELECT MBMS_Movie__c
                                          FROM MBMS_Movie_Actor__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movieActor.MBMS_Movie__c);
    }
}