src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieActorBuilder.cls
public class MovieActorBuilder {
    private MBMS_Movie_Actor__c movieActor;
    
    public MovieActorBuilder() {
        this.movieActor = new MBMS_Movie_Actor__c();
    }
    
    public MovieActorBuilder withActor(MBMS_Artist__c artist) {
        this.movieActor.MBMS_Artist__c = artist.Id;
        return this;
    }
    
    public MovieActorBuilder withMovie(MBMS_Movie__c movie) {
        this.movieActor.MBMS_Movie__c = movie.Id;
        return this;
    }
    
    public MBMS_Movie_Actor__c buildWithAllFields() {
        MBMS_Artist__c artist = new ArtistBuilder().buildWithAllFieldsAndInsert();
        MBMS_Movie__c movie = new MovieBuilder().buildWithAllFieldsAndInsert();
        
        return this
            .withActor(artist)
            .withMovie(movie)
            .build();
    }
    
    public MBMS_Movie_Actor__c buildWithAllFieldsAndInsert() {
        this.movieActor = this.buildWithAllFields();
        insert movieActor;
        return movieActor;
    }
    
    public MBMS_Movie_Actor__c build() {       
        return movieActor;
    }
    
    public MBMS_Movie_Actor__c buildAndInsert() {       
        insert movieActor;
        return this.build();
    }
}