src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Artist.</description>
        <inlineHelpText>Description of the artist.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Artist.</description>
    <inlineHelpText>Artist status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Book author.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Cover_Image_URL__c</fullName>
        <description>A field that stores a cover image URL of the Book.</description>
        <inlineHelpText>URL of the Book cover image.</inlineHelpText>
        <label>Cover Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Book.</description>
        <inlineHelpText>Description of the Book.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Book.</description>
        <inlineHelpText>Book status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Book record.</description>
        <inlineHelpText>Status of the Book record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookBuilderTest.cls
@isTest
private class BookBuilderTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        new BookBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void bookShouldNotBeNull() {
        MBMS_Book__c book = new BookBuilder()
            .create()
            .build();
        
        System.assertNotEquals(null, book, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Book__c' }));
    }
    
    @isTest
    static void insertedBookShouldNotBeNull() {
        MBMS_Book__c book = [
            SELECT
                Id
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, book, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Book__c' }));
    }
    
    @isTest
    static void bookShouldHaveArtist() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Artist__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, book.MBMS_Artist__c, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist__c' }));
    }
    
    @isTest
    static void bookShouldHaveName() {
        MBMS_Book__c book = [
            SELECT
                Name
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, book.Name, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'Name' }));
    }
    
    @isTest
    static void bookShouldHaveDescription() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Description__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, book.MBMS_Description__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Description__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookShouldHaveTitle() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Title__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, book.MBMS_Title__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Title__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookShouldHaveCoverImageURL() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Cover_Image_URL__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, book.MBMS_Cover_Image_URL__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Cover_Image_URL__c', Constants.TEST_STRING_VALUE }));
    }

    @isTest
    static void bookShouldHaveStatus() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Status__c
            FROM MBMS_Book__c
            LIMIT 1
        ];

        System.assertEquals(Constants.STATUS_APPROVED, book.MBMS_Status__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status__c', Constants.STATUS_APPROVED }));
    }
    
    @isTest
    static void bookShouldHaveStatusComment() {
        MBMS_Book__c book = [
            SELECT
                MBMS_Status_Comment__c
            FROM MBMS_Book__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.INITIAL_STATUS_COMMENT, book.MBMS_Status_Comment__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status_Comment__c', Constants.INITIAL_STATUS_COMMENT }));
    }
}