src/objects/MBMS_Author__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies</relationshipLabel>
        <relationshipName>Movies_Director</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writer</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies (Writer)</relationshipLabel>
        <relationshipName>Movies_Writer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieBuilderTest.cls
@isTest
private class MovieBuilderTest {
    @testSetup
    static void testDataSetup() {
        MBMS_Author__c author = new AuthorBuilder()
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .buildAndInsert();
        
        MBMS_Movie__c movie = new MovieBuilder()
            .withDescription(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withDirector(author)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withWriter(author)
            .buildAndInsert();
    }
    
    @isTest
    static void movieShouldNotBeNull() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT Id
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movie);
    }
    
    @isTest
    static void movieShouldHaveADescription() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT MBMS_Description__c
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, movie.MBMS_Description__c);
    }
    
    @isTest
    static void movieShouldHaveADirector() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT MBMS_Director__c
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movie.MBMS_Director__c);
    }
    
    @isTest
    static void movieShouldHaveAName() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT Name
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, movie.Name);
    }
    
    @isTest
    static void movieShouldHaveATitle() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT MBMS_Title__c
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, movie.MBMS_Title__c);
    }
    
    @isTest
    static void movieShouldHaveAWriter() {
        Test.startTest();        
        MBMS_Movie__c movie = [SELECT MBMS_Writer__c
                               FROM MBMS_Movie__c
                               LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, movie.MBMS_Writer__c);
    }
}