src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie_Actor__c/fields/MBMS_Character_Name__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Character_Name__c</fullName>
    <description>A field that stores the name of the character played by the actor.</description>
    <inlineHelpText>Character name.</inlineHelpText>
    <label>Character Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/MovieActorTriggerHandler.cls
public class MovieActorTriggerHandler {
    public void onBeforeInsert(List<MBMS_Movie_Actor__c> movieActors) {
        List<Id> actorsIds = new List<Id>();
        
        for (MBMS_Movie_Actor__c movieActor : movieActors) {
            actorsIds.add(movieActor.MBMS_Artist__c);
        }
        
        List<MBMS_Artist__c> actors = [SELECT Name FROM MBMS_Artist__c WHERE Id IN :actorsIds];
        
        for (Integer i = 0; i < movieActors.size(); i++) {
            movieActors[i].Name = String.format('{0} as {1}', new List<String> { actors[i].Name, movieActors[i].MBMS_Character_Name__c });
        }
    }
}