src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Artist_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist News.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Artist News</relationshipLabel>
        <relationshipName>Artist_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Artist News</label>
    <nameField>
        <label>Artist News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artist News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ArtistNewsControllerTest.cls
@isTest
public class ArtistNewsControllerTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        new ArtistNewsBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void shouldThrowException() {
        MBMS_Artist_News__c artistNews = [
            SELECT
                Id
            FROM MBMS_Artist_News__c
            LIMIT 1
        ];
        
        delete artistNews;
        
        Integer exceptionsCount = 0;
        
        Test.startTest();
        try {
            artistNews = ArtistNewsController.getLatestArtistNews();
        } catch (Exception e) {
            exceptionsCount++;
            System.assertNotEquals(null, e, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'Exception' }));
            System.assertEquals(Constants.NO_ROWS_FOR_ASSIGMENT, e.getMessage(), String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { Constants.NO_ROWS_FOR_ASSIGMENT }));
        }
        Test.stopTest();
        
        System.assert(exceptionsCount > 0, String.format(Constants.VALUE_SHOULD_BE_GREATER_THAN_PATTERN, new List<String> { 'exceptionsCount', '0' }));
    }
    
    @isTest
    static void shouldReturnArtistNews() {
        Test.startTest();
        MBMS_Artist_News__c artistNews = ArtistNewsController.getLatestArtistNews();
        Test.stopTest();
        
        System.assertNotEquals(null, artistNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist_News__c' }));
    }
    
    @isTest
    static void shouldReturnArtistNewsByArtistId() {
        MBMS_Artist__c artist = [
            SELECT
                Id
            FROM MBMS_Artist__c
            LIMIT 1
        ];

        Test.startTest();
        MBMS_Artist_News__c artistNews = ArtistNewsController.getLatestArtistNewsByArtistId(artist.Id);
        Test.stopTest();
        
        System.assertNotEquals(null, artistNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Artist_News__c' }));
    }
}