src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Birthplace__c</fullName>
        <description>A field that stores a birthplace (country / city) of the Artist.</description>
        <inlineHelpText>Birthplace of the artist.</inlineHelpText>
        <label>Birthplace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Date_of_Birth__c</fullName>
        <description>A field that stores a date of birth of the Artist.</description>
        <inlineHelpText>Date of birth of the artist.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MBMS_Date_of_Death__c</fullName>
        <description>A field that stores a date of death of the Artist.</description>
        <inlineHelpText>Date of death of the artist.</inlineHelpText>
        <label>Date of Death</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Artist.</description>
        <inlineHelpText>Description of the artist.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Roles__c</fullName>
        <description>A field that stores a roles of the Artist.</description>
        <inlineHelpText>Roles of the artist.</inlineHelpText>
        <label>Roles</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>MBMS_Author</fullName>
                    <label>Author</label>
                </value>
                <value>
                    <fullName>MBMS_Actor</fullName>
                    <label>Actor</label>
                </value>
                <value>
                    <fullName>MBMS_Director</fullName>
                    <label>Director</label>
                </value>
                <value>
                    <fullName>MBMS_Writer</fullName>
                    <label>Writer</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_First_Name__c.field-meta.xml
<CustomField>
    <fullName>MBMS_First_Name__c</fullName>
    <description>A field that stores a first name of the Artist.</description>
    <inlineHelpText>First name of the Artist.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Last_Name__c</fullName>
    <description>A field that stores a last name of the Artist.</description>
    <inlineHelpText>Last name of the Artist.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Artist.</description>
    <inlineHelpText>Artist status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/classes/ArtistBuilder.cls
public class ArtistBuilder {
    private MBMS_Artist__c artist;
    
    public ArtistBuilder create() {
        this.artist = new MBMS_Artist__c();
        return this;
    }
    
    public ArtistBuilder withName(String name) {
        this.artist.Name = name;
        return this;
    }
    
    public ArtistBuilder withFirstName(String firstName) {
        this.artist.MBMS_First_Name__c = firstName;
        return this;
    }
    
    public ArtistBuilder withLastName(String lastName) {
        this.artist.MBMS_Last_Name__c = lastName;
        return this;
    }
    
    public ArtistBuilder withBirthplace(String birthplace) {
        this.artist.MBMS_Birthplace__c = birthplace;
        return this;
    }
    
    public ArtistBuilder withDateOfBirth(Date dateOfBirth) {
        this.artist.MBMS_Date_of_Birth__c = dateOfBirth;
        return this;
    }
    
    public ArtistBuilder withDateOfDeath(Date dateOfDeath) {
        this.artist.MBMS_Date_of_Death__c = dateOfDeath;
        return this;
    }
    
    public ArtistBuilder withDescription(String description) {
        this.artist.MBMS_Description__c = description;
        return this;
    }
    
    public ArtistBuilder withRoles(List<String> roles) {
        this.artist.MBMS_Roles__c = String.join(roles, ';');
        return this;
    }

    public ArtistBuilder withStatus(String status) {
        this.artist.MBMS_Status__c = status;
        return this;
    }
    
    public ArtistBuilder withStatusComment(String statusComment) {
        this.artist.MBMS_Status_Comment__c = statusComment;
        return this;
    }
    
    public MBMS_Artist__c buildWithAllFields() {
        return this
            .withName(Constants.TEST_STRING_VALUE)
            .withFirstName(Constants.TEST_STRING_VALUE)
            .withLastName(Constants.TEST_STRING_VALUE)
            .withBirthplace(Constants.TEST_STRING_VALUE)
            .withDateOfBirth(Constants.TEST_DATE_200_DAYS_BEFORE_TODAY)
            .withDateOfDeath(Constants.TEST_DATE_10_DAYS_BEFORE_TODAY)
            .withDescription(Constants.TEST_STRING_VALUE)
            .withRoles(new List<String> { Constants.ROLE_AUTHOR, Constants.ROLE_ACTOR })
            .withStatus(Constants.STATUS_APPROVED)
            .withStatusComment(Constants.TEST_STRING_VALUE)
            .build();
    }
    
    public MBMS_Artist__c buildWithAllFieldsAndInsert() {
        this.artist = this.buildWithAllFields();
        insert artist;
        return artist;
    }
    
    public MBMS_Artist__c build() {       
        return this.artist;
    }
    
    public MBMS_Artist__c buildAndInsert() {       
        insert this.artist;
        return this.build();
    }
}