src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Book News.</description>
    <fields>
        <fullName>MBMS_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Book object.</description>
        <inlineHelpText>Book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>MBMS_Book__c</referenceTo>
        <relationshipLabel>Book News</relationshipLabel>
        <relationshipName>Book_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book News</label>
    <nameField>
        <label>Book News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookNewsBuilderTest.cls
@isTest
private class BookNewsBuilderTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        new BookNewsBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void bookNewsShouldNotBeNull() {
        MBMS_Book_News__c bookNews = new BookNewsBuilder()
            .create()
            .build();
        
        System.assertNotEquals(null, bookNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Book_News__c' }));
    }
    
    @isTest
    static void insertedBookNewsShouldNotBeNull() {
        MBMS_Book_News__c bookNews = [
            SELECT
                Id
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, bookNews, String.format(Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Book_News__c' }));
    }
    
    @isTest
    static void bookNewsShouldHaveName() {
        MBMS_Book_News__c bookNews = [
            SELECT
                Name
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, bookNews.Name, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'Name', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookNewsShouldHaveTitle() {
        MBMS_Book_News__c bookNews = [
            SELECT
                MBMS_Title__c
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, bookNews.MBMS_Title__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Title__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookNewsShouldHaveContent() {
        MBMS_Book_News__c bookNews = [
            SELECT
                MBMS_Content__c
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, bookNews.MBMS_Content__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Content__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookNewsShouldHaveTags() {
        MBMS_Book_News__c bookNews = [
            SELECT
                MBMS_Tags__c
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assert(bookNews.MBMS_Tags__c.contains(Constants.TEST_STRING_VALUE), String.format(Constants.FIELD_SHOULD_CONTAIN_PATTERN, new List<String> { 'MBMS_Tags__c', Constants.TEST_STRING_VALUE }));
    }
    
    @isTest
    static void bookNewsShouldHaveArtist() {
        MBMS_Book_News__c bookNews = [
            SELECT
                MBMS_Book__c
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertNotEquals(null, bookNews.MBMS_Book__c, String.format(Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Book__c' }));
    }
    
    @isTest
    static void bookNewsShouldHaveImageURL() {
        MBMS_Book_News__c bookNews = [
            SELECT
                MBMS_Image_URL__c
            FROM MBMS_Book_News__c
            LIMIT 1
        ];
        
        System.assertEquals(Constants.TEST_STRING_VALUE, bookNews.MBMS_Image_URL__c, String.format(Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Image_URL__c', Constants.TEST_STRING_VALUE }));
    }
}