src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Artist_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist News.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Artist News</relationshipLabel>
        <relationshipName>Artist_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist News</label>
    <nameField>
        <label>Artist News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artist News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ArtistNewsBuilderTest.cls
@isTest
private class ArtistNewsBuilderTest {
    @testSetup
    static void testDataSetup() {
        new ArtistNewsBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
    }
    
    @isTest
    static void artistNewsShouldNotBeNull() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = new ArtistNewsBuilder()
            .create()
            .build();
        Test.stopTest();
        
        System.assertNotEquals(null, artistNews);
    }
    
    @isTest
    static void insertedArtistNewsShouldNotBeNull() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT Id
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, artistNews);
    }
    
    @isTest
    static void artistNewsShouldHaveName() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT Name
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, artistNews.Name);
    }
    
    @isTest
    static void artistNewsShouldHaveTitle() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT MBMS_Title__c
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, artistNews.MBMS_Title__c);
    }
    
    @isTest
    static void artistNewsShouldHaveContent() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT MBMS_Content__c
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, artistNews.MBMS_Content__c);
    }
    
    @isTest
    static void artistNewsShouldHaveTags() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT MBMS_Tags__c
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assert(artistNews.MBMS_Tags__c.contains(MBMS_Constants.MBMS_TEST_STRING_VALUE));
        System.assert(artistNews.MBMS_Tags__c.contains(';'));
    }
    
    @isTest
    static void artistNewsShouldHaveArtist() {
        Test.startTest();        
        MBMS_Artist_News__c artistNews = [SELECT MBMS_Artist__c
                                          FROM MBMS_Artist_News__c
                                          LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, artistNews.MBMS_Artist__c);
    }
}