src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Artist.</description>
        <inlineHelpText>Description of the artist.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies</relationshipLabel>
        <relationshipName>Movies_Director</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBMS_Writer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Writer</label>
        <referenceTo>MBMS_Author__c</referenceTo>
        <relationshipLabel>Movies (Writer)</relationshipLabel>
        <relationshipName>Movies_Writer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

src/classes/MovieBuilder.cls
public class MovieBuilder {   
    private MBMS_Movie__c movie;
    
    public MovieBuilder() {
        this.movie = new MBMS_Movie__c();
    }
    
    public MovieBuilder withDescription(String description) {
        this.movie.MBMS_Description__c = description;
        return this;
    }
    
    public MovieBuilder withDirector(MBMS_Artist__c director) {
        this.movie.MBMS_Director__c = director.Id;
        return this;
    }
    
    public MovieBuilder withName(String name) {
        this.movie.Name = name;
        return this;
    }
    
    public MovieBuilder withTitle(String title) {
        this.movie.MBMS_Title__c = title;
        return this;
    }
    
    public MovieBuilder withWriter(MBMS_Artist__c writer) {
        this.movie.MBMS_Writer__c = writer.Id;
        return this;
    }
    
    public MovieBuilder withStatus(String status) {
        this.movie.MBMS_Status__c = status;
        return this;
    }
    
    public MBMS_Movie__c buildWithAllFields() {
        MBMS_Artist__c artist = new ArtistBuilder().buildWithAllFieldsAndInsert();
        
        return this
            .withDescription(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withDirector(artist)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withWriter(artist)
            .withStatus(MBMS_Constants.MBMS_STATUS_APPROVED)
            .build();
    }
    
    public MBMS_Movie__c buildWithAllFieldsAndInsert() {
        this.movie = this.buildWithAllFields();
        insert movie;
        return movie;
    }
    
    public MBMS_Movie__c build() {       
        return movie;
    }
    
    public MBMS_Movie__c buildAndInsert() {       
        insert movie;
        return this.build();
    }
}