src/objects/MBMS_Movie__c.object
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

src/classes/MoviesRemovalBatch.cls
public class MoviesRemovalBatch extends VirtualBatchRunLogger implements Database.Batchable<sObject>, Database.Stateful {
    public MoviesRemovalBatch() {
        super(String.valueOf(MoviesRemovalBatch.class));
    }
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        startLogging();
        return Database.getQueryLocator([SELECT Id
                                         FROM MBMS_Movie__c
                                         WHERE MBMS_Status__c IN (:MBMS_Constants.MBMS_STATUS_INITIAL,
                                                                  :MBMS_Constants.MBMS_STATUS_REJECTED)
                                         AND CreatedDate <= :MBMS_Constants.MBMS_RECORDS_RETENTION_DATE]);
    }
    
    public void execute(Database.BatchableContext context, List<MBMS_Movie__c> movies) {
        List<Database.DeleteResult> deleteResults = Database.delete(movies);
        
        for (Database.DeleteResult result : deleteResults) {
            if (result.isSuccess()) {
                incrementSuccessesCount();
                continue;
            }
            
            for (Database.Error error : result.getErrors()) {
                logErrorMessage(error.getMessage());
            }
        }
    }
    
    public void finish(Database.BatchableContext context) {
        stopLogging();
    }
}