src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Artist.</description>
    <inlineHelpText>Artist status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Movie.</description>
    <inlineHelpText>Movie status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MovieTriggerUtility.cls
public class MovieTriggerUtility {
    public static void updateMovieNames(List<MBMS_Movie__c> movies) {
        for (MBMS_Movie__c movie : movies) {
            movie.Name = movie.MBMS_Title__c;
        }
    }
    
    public static void updateMovieStatusComments(List<MBMS_Movie__c> movies) {
        for (MBMS_Movie__c movie : movies) {
            movie.MBMS_Status_Comment__c = MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT;
        }
    }
    
    public static void removeRelatedMovieActors(List<MBMS_Movie__c> movies) {
        Set<Id> movieIds = (new Map<Id, MBMS_Movie__c>(movies)).keySet();
        List<MBMS_Movie_Actor__c> movieActors = [SELECT Id FROM MBMS_Movie_Actor__c WHERE MBMS_Artist__r.Id IN :movieIds];
        
        delete movieActors;
    }
}