src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Artist.</description>
        <inlineHelpText>Description of the artist.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Book author.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Cover_Image_URL__c</fullName>
        <description>A field that stores a cover image URL of the Book.</description>
        <inlineHelpText>URL of the Book cover image.</inlineHelpText>
        <label>Cover Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Book.</description>
        <inlineHelpText>Description of the Book.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Book record.</description>
        <inlineHelpText>Status of the Book record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookBuilder.cls
public class BookBuilder {   
    private MBMS_Book__c book;
    
    public BookBuilder() {
        this.book = new MBMS_Book__c();
    }
    
    public BookBuilder withArtist(MBMS_Artist__c artist) {
        this.book.MBMS_Artist__c = artist.Id;
        return this;
    }
    
    public BookBuilder withName(String name) {
        this.book.Name = name;
        return this;
    }
    
    public BookBuilder withDescription(String description) {
        this.book.MBMS_Description__c = description;
        return this;
    }
    
    public BookBuilder withTitle(String title) {
        this.book.MBMS_Title__c = title;
        return this;
    }
    
    public BookBuilder withCoverImageURL(String coverImageURL) {
        this.book.MBMS_Cover_Image_URL__c = coverImageURL;
        return this;
    }

    public BookBuilder withStatus(String status) {
        this.book.MBMS_Status__c = status;
        return this;
    }
    
    public MBMS_Book__c build() {       
        return book;
    }
    
    public MBMS_Book__c buildAndInsert() {       
        insert book;
        return this.build();
    }
}