src/objects/MBMS_Movie_Photo__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie Photo.</description>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Movie Photo.</description>
        <inlineHelpText>Movie Photo status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Movie Photo record.</description>
        <inlineHelpText>Status of the Movie Photo record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Movie Photo</label>
    <nameField>
        <label>Movie Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoviePhotoTriggerHandlerTest.cls
@isTest
private class MoviePhotoTriggerHandlerTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        MBMS_Movie_Photo__c book = new MoviePhotoBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void triggerShouldUpdateMoviePhotoStatusComment() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT MBMS_Status_Comment__c
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertEquals(MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT, moviePhoto.MBMS_Status_Comment__c, String.format(MBMS_Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status_Comment__c', MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT }));
    }

    @isTest
    static void triggerShouldUpdateRecordOwner() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT OwnerId
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];  
        moviePhoto.MBMS_Status__c = MBMS_Constants.MBMS_STATUS_REJECTED;

        Test.startTest();
        update moviePhoto;
        Test.stopTest();

        Group approversQueue = [SELECT Id
                                FROM Group WHERE Type = :MBMS_Constants.QUEUE_GROUP_TYPE
                                AND Name = :MBMS_Constants.APPROVERS_QUEUE
                                LIMIT 1];

        moviePhoto = [SELECT OwnerId
                      FROM MBMS_Movie_Photo__c
                      LIMIT 1];
        
        System.assertEquals(approversQueue.Id, moviePhoto.OwnerId, String.format(MBMS_Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'OwnerId', approversQueue.Id }));
    }
}