src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book_News__c.object
<CustomObject>
    <description>This is an object for storing information about the Book News.</description>
    <fields>
        <fullName>MBMS_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Book object.</description>
        <inlineHelpText>Book.</inlineHelpText>
        <label>Book</label>
        <referenceTo>MBMS_Book__c</referenceTo>
        <relationshipLabel>Book News</relationshipLabel>
        <relationshipName>Book_News</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Content__c</fullName>
        <description>A field that stores the news content.</description>
        <inlineHelpText>News content.</inlineHelpText>
        <label>Content</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Image_URL__c</fullName>
        <description>A field that stores an URL of the News image.</description>
        <inlineHelpText>URL of news image.</inlineHelpText>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Tags__c</fullName>
        <description>A field that stores comma separated news tags.</description>
        <inlineHelpText>News tags.</inlineHelpText>
        <label>Tags</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores the news title.</description>
        <inlineHelpText>News title.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book News</label>
    <nameField>
        <label>Book News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Book News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookNewsController.cls
public with sharing class BookNewsController {
    @AuraEnabled(cacheable=true)
    public static MBMS_Book_News__c getLatestBookNews() {
        return [SELECT MBMS_Title__c, MBMS_Content__c, MBMS_Tags__c, MBMS_Image_URL__c, CreatedDate
                FROM MBMS_Book_News__c
                ORDER BY CreatedDate DESC
                LIMIT 1];
    }
    
    @AuraEnabled(cacheable=true)
    public static MBMS_Book_News__c getLatestBookNewsByBookId(String bookId) {
        return [SELECT MBMS_Title__c, MBMS_Content__c, MBMS_Tags__c, MBMS_Image_URL__c, CreatedDate, MBMS_Book__r.Name
                FROM MBMS_Book_News__c
                WHERE MBMS_Book__c = :bookId
                ORDER BY CreatedDate DESC
                LIMIT 1];
    }
}