src/objects/MBMS_Author__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBMS_Book__c.object
<CustomObject>
    <description>This is an object for storing information about the Book.</description>
    <fields>
        <fullName>MBMS_Cover_Image_URL__c</fullName>
        <description>A field that stores a cover image URL of the Book.</description>
        <inlineHelpText>URL of the Book cover image.</inlineHelpText>
        <label>Cover Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Description__c</fullName>
        <description>A field that stores a description of the Book.</description>
        <inlineHelpText>Description of the Book.</inlineHelpText>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Book.</description>
        <inlineHelpText>Title of the Book.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookBuilderTest.cls
@isTest
private class BookBuilderTest {
    @testSetup
    static void testDataSetup() {
        MBMS_Author__c author = new AuthorBuilder()
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .buildAndInsert();
        
        MBMS_Book__c book = new BookBuilder()
            .withAuthor(author)
            .withName(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withDescription(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withTitle(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .withCoverImageURL(MBMS_Constants.MBMS_TEST_STRING_VALUE)
            .buildAndInsert();
    }
    
    @isTest
    static void bookShouldNotBeNull() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT Id
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, book);
    }
    
    @isTest
    static void bookShouldHaveAnAuthor() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT MBMS_Author__c
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, book.MBMS_Author__c);
    }
    
    @isTest
    static void bookShouldHaveAName() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT Name
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, book.Name);
    }
    
    @isTest
    static void bookShouldHaveADescription() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT MBMS_Description__c
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, book.MBMS_Description__c);
    }
    
    @isTest
    static void bookShouldHaveATitle() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT MBMS_Title__c
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, book.MBMS_Title__c);
    }
    
    @isTest
    static void bookShouldHaveACoverImageURL() {
        Test.startTest();        
        MBMS_Book__c book = [SELECT MBMS_Cover_Image_URL__c
                             FROM MBMS_Book__c
                             LIMIT 1];
        Test.stopTest();
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, book.MBMS_Cover_Image_URL__c);
    }
}