src/objects/MBMS_Movie__c.object
<CustomObject>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Movie.</description>
    <inlineHelpText>Movie status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie_Photo__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie Photo.</description>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipName>Photos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Photo_URL__c</fullName>
        <description>A field that stores a Photo URL.</description>
        <inlineHelpText>Photo URL.</inlineHelpText>
        <label>Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Movie Photo.</description>
        <inlineHelpText>Movie Photo status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Movie Photo record.</description>
        <inlineHelpText>Status of the Movie Photo record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Movie Photo</label>
    <nameField>
        <label>Movie Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MoviePhotoBuilderTest.cls
@isTest
private class MoviePhotoBuilderTest {
    @testSetup
    static void testDataSetup() {
        Test.startTest();
        new MoviePhotoBuilder()
            .create()
            .buildWithAllFieldsAndInsert();
        Test.stopTest();
    }
    
    @isTest
    static void moviePhotoShouldNotBeNull() {
        MBMS_Movie_Photo__c moviePhoto = new MoviePhotoBuilder()
            .create()
            .build();
        
        System.assertNotEquals(null, moviePhoto, String.format(MBMS_Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Movie_Photo__c' }));
    }
    
    @isTest
    static void insertedMoviePhotoShouldNotBeNull() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT Id
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertNotEquals(null, moviePhoto, String.format(MBMS_Constants.OBJECT_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Movie_Photo__c' }));
    }
    
    @isTest
    static void moviePhotoShouldHaveMovie() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT MBMS_Movie__c
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertNotEquals(null, moviePhoto.MBMS_Movie__c, String.format(MBMS_Constants.FIELD_SHOULD_NOT_BE_NULL_PATTERN, new List<String> { 'MBMS_Movie__c' }));
    }

    @isTest
    static void moviePhotoShouldHavePhotoURL() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT MBMS_Photo_URL__c
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertEquals(MBMS_Constants.MBMS_TEST_STRING_VALUE, moviePhoto.MBMS_Photo_URL__c, String.format(MBMS_Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Photo_URL__c', MBMS_Constants.MBMS_TEST_STRING_VALUE }));
    }

    @isTest
    static void moviePhotoShouldHaveStatus() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT MBMS_Status__c
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertEquals(MBMS_Constants.MBMS_STATUS_APPROVED, moviePhoto.MBMS_Status__c, String.format(MBMS_Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status__c', MBMS_Constants.MBMS_STATUS_APPROVED }));
    }
    
    @isTest
    static void moviePhotoShouldHaveStatusComment() {
        MBMS_Movie_Photo__c moviePhoto = [SELECT MBMS_Status_Comment__c
                                          FROM MBMS_Movie_Photo__c
                                          LIMIT 1];
        
        System.assertEquals(MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT, moviePhoto.MBMS_Status_Comment__c, String.format(MBMS_Constants.FIELD_SHOULD_BE_PATTERN, new List<String> { 'MBMS_Status_Comment__c', MBMS_Constants.MBMS_INITIAL_STATUS_COMMENT }));
    }
}