src/objects/MBMS_Movie_Photo__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie Photo.</description>
    <fields>
        <fullName>MBMS_Status_Comment__c</fullName>
        <description>A field that stores a comment related to the status of the Movie Photo.</description>
        <inlineHelpText>Movie Photo status comment.</inlineHelpText>
        <label>Status Comment</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Movie Photo record.</description>
        <inlineHelpText>Status of the Movie Photo record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Movie Photo</label>
    <nameField>
        <label>Movie Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie_Photo__c/fields/MBMS_Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Previous_Status__c</fullName>
    <description>A field that stores a previous status of the Movie Photo record.</description>
    <inlineHelpText>Previous Status of the Movie Photo record.</inlineHelpText>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/MoviePhotoTriggerUtility.cls
public class MoviePhotoTriggerUtility {
    public static void updateMoviePhotoStatusComments(List<MBMS_Movie_Photo__c> moviePhotos) {
        for (MBMS_Movie_Photo__c moviePhoto : moviePhotos) {
            moviePhoto.MBMS_Status_Comment__c = Constants.INITIAL_STATUS_COMMENT;
        }
    }

    public static void updatePreviousStatus(List<MBMS_Movie_Photo__c> oldMoviePhotos, List<MBMS_Movie_Photo__c> newMoviePhotos) {
        for (Integer i = 0; i < newMoviePhotos.size(); i++) {
            newMoviePhotos[i].MBMS_Previous_Status__c = oldMoviePhotos[i].MBMS_Status__c;
        }
    }

    public static void notifyApprovers(List<MBMS_Movie_Photo__c> moviePhotos) {
        Group approversQueue = SObjectsSelector.getApproversQueue();
        List<GroupMember> approvers = SObjectsSelector.getGroupMembersByGroupId(approversQueue.Id);

        Set<String> approversIds = new Set<String>();
        
        for (GroupMember approver : approvers) {
            approversIds.add(approver.UserOrGroupId);
        }
        
        for (MBMS_Movie_Photo__c moviePhoto : moviePhotos) {
            if (moviePhoto.MBMS_Status__c.equals(moviePhoto.MBMS_Previous_Status__c)) {
                continue;
            }

            if (moviePhoto.MBMS_Status__c.equals(Constants.STATUS_APPROVED)) {
                continue;
            }
            
            moviePhoto.OwnerId = approversQueue.Id;
            
            new CustomNotificationBuilder().create()
                .withTitle(Constants.PLEASE_TAKE_ACTION)
                .withBody(String.format(Constants.RECORD_TO_APPROVE_PATTERN, new List<String> { moviePhoto.Name, moviePhoto.Id }))
                .withDefaultNotificationType()
                .withTargetId(moviePhoto.Id)
                .build()
                .send(approversIds);
        }
    }
}