src/objects/MBMS_Artist__c.object
<CustomObject>
    <description>This is an object for storing information about the Artist.</description>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Artist record.</description>
        <inlineHelpText>Status of the Artist record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <description>A field that stores a title of the Artist.</description>
        <inlineHelpText>Title of the artist.</inlineHelpText>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Artist</label>
    <nameField>
        <label>Artist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Previous_Status__c</fullName>
    <description>A field that stores a previous status of the Artist record.</description>
    <inlineHelpText>Previous Status of the Artist record.</inlineHelpText>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBMS_Artist__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Artist.</description>
    <inlineHelpText>Artist status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Previous_Status__c</fullName>
    <description>A field that stores a previous status of the Movie record.</description>
    <inlineHelpText>Previous Status of the Movie record.</inlineHelpText>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status_Comment__c</fullName>
    <description>A field that stores a comment related to the status of the Movie.</description>
    <inlineHelpText>Movie status comment.</inlineHelpText>
    <label>Status Comment</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/MBMS_Movie_Actor__c.object
<CustomObject>
    <description>Junction object between Movie and Artist.</description>
    <fields>
        <fullName>MBMS_Artist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Artist object.</description>
        <inlineHelpText>Artist.</inlineHelpText>
        <label>Artist</label>
        <referenceTo>MBMS_Artist__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipLabel>Movie Actors</relationshipLabel>
        <relationshipName>Movie_Actors</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Movie Actor</label>
    <nameField>
        <label>Movie Actor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Actors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MovieTriggerUtility.cls
public class MovieTriggerUtility {
    public static void updateMovieNames(List<MBMS_Movie__c> movies) {
        for (MBMS_Movie__c movie : movies) {
            movie.Name = movie.MBMS_Title__c;
        }
    }
    
    public static void updateMovieStatusComments(List<MBMS_Movie__c> movies) {
        for (MBMS_Movie__c movie : movies) {
            movie.MBMS_Status_Comment__c = Constants.INITIAL_STATUS_COMMENT;
        }
    }

    public static void updatePreviousStatus(List<MBMS_Movie__c> oldMovies, List<MBMS_Movie__c> newMovies) {
        for (Integer i = 0; i < newMovies.size(); i++) {
            newMovies[i].MBMS_Previous_Status__c = oldMovies[i].MBMS_Status__c;
        }
    }
    
    public static void removeRelatedMovieActors(List<MBMS_Movie__c> movies) {
        Set<Id> movieIds = (new Map<Id, MBMS_Movie__c>(movies)).keySet();
        List<MBMS_Movie_Actor__c> movieActors = [
            SELECT
                Id
            FROM MBMS_Movie_Actor__c
            WHERE MBMS_Artist__r.Id IN :movieIds
        ];
        
        delete movieActors;
    }

    public static void notifyApprovers(List<MBMS_Movie__c> movies) {
        Group approversQueue = SObjectsSelector.getApproversQueue();
        List<GroupMember> approvers = SObjectsSelector.getGroupMembersByGroupId(approversQueue.Id);

        Set<String> approversIds = new Set<String>();
        
        for (GroupMember approver : approvers) {
            approversIds.add(approver.UserOrGroupId);
        }
        
        for (MBMS_Movie__c movie : movies) {
            if (movie.MBMS_Status__c == movie.MBMS_Previous_Status__c) {
                continue;
            }

            if (movie.MBMS_Status__c == Constants.STATUS_APPROVED) {
                continue;
            }
            
            movie.OwnerId = approversQueue.Id;
            
            new CustomNotificationBuilder().create()
                .withTitle(Constants.PLEASE_TAKE_ACTION)
                .withBody(String.format(Constants.RECORD_TO_APPROVE_PATTERN, new List<String> { movie.Name, movie.Id }))
                .withDefaultNotificationType()
                .withTargetId(movie.Id)
                .build()
                .send(approversIds);
        }
    }
}