src/objects/MBMS_Movie__c.object
<CustomObject>
    <fields>
        <fullName>MBMS_Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MBMS_Movie__c/fields/MBMS_Status__c.field-meta.xml
<CustomField>
    <fullName>MBMS_Status__c</fullName>
    <description>A field that stores a status of the Movie record.</description>
    <inlineHelpText>Status of the Movie record.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MBMS_Status_Values</valueSetName>
    </valueSet>
</CustomField>

src/objects/MBMS_Movie_Photo__c.object
<CustomObject>
    <description>This is an object for storing information about the Movie Photo.</description>
    <fields>
        <fullName>MBMS_Movie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A field that stores a lookup to the Movie object.</description>
        <inlineHelpText>Movie.</inlineHelpText>
        <label>Movie</label>
        <referenceTo>MBMS_Movie__c</referenceTo>
        <relationshipName>Photos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBMS_Photo_URL__c</fullName>
        <description>A field that stores a Photo URL.</description>
        <inlineHelpText>Photo URL.</inlineHelpText>
        <label>Photo URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MBMS_Status__c</fullName>
        <description>A field that stores a status of the Movie Photo record.</description>
        <inlineHelpText>Status of the Movie Photo record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>MBMS_Status_Values</valueSetName>
        </valueSet>
    </fields>
    <label>Movie Photo</label>
    <nameField>
        <label>Movie Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movie Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MoviePhotosListController.cls
public with sharing class MoviePhotosListController {
    public final static Integer MINIMUM_NUMBER_OF_PHOTOS = 4;
    
    @AuraEnabled
    public static List<MBMS_Movie_Photo__c> getPhotos() {
        return [
            SELECT
                Id,
                MBMS_Photo_URL__c
            FROM MBMS_Movie_Photo__c
        ];
    }
    
    @AuraEnabled
    public static List<MBMS_Movie_Photo__c> getLatestPhotos() {
        return [
            SELECT
                Id,
                Name,
                MBMS_Photo_URL__c,
                MBMS_Movie__r.MBMS_Title__c
            FROM MBMS_Movie_Photo__c
            ORDER BY CreatedDate DESC
            LIMIT :MINIMUM_NUMBER_OF_PHOTOS
        ];
    }
    
    public static List<MBMS_Movie_Photo__c> getRequiringActionPhotos() {
        return [
            SELECT
                Id,
                Name,
                MBMS_Status__c,
                CreatedDate
            FROM MBMS_Movie_Photo__c
            WHERE MBMS_Status__c
            IN (:Constants.STATUS_INITIAL, :Constants.STATUS_REJECTED)
            ORDER BY CreatedDate
        ];
    }
    
    @AuraEnabled
    public static Boolean arePhotosAvailable() { 
        return getLatestPhotos().size().equals(MINIMUM_NUMBER_OF_PHOTOS);
    }
    
    @AuraEnabled
    public static Integer getMinimumNumberOfPhotos() {
        return MINIMUM_NUMBER_OF_PHOTOS;
    }
}